"""FilReview added with new column review

Revision ID: bbef224a537d
Revises: 9e1b1adfe339
Create Date: 2025-04-09 00:22:05.868269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbef224a537d'
down_revision: Union[str, None] = '9e1b1adfe339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_review', sa.Column('review', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_review', 'review')
    # ### end Alembic commands ###
