"""added code_language column for FileReview table

Revision ID: ed2377d92af6
Revises: bbef224a537d
Create Date: 2025-04-09 21:43:20.636246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed2377d92af6"
down_revision: Union[str, None] = "bbef224a537d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file_review",
        sa.Column(
            "code_language",
            sa.String(length=120),
            nullable=True,
            server_default="python",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_review", "code_language")
    # ### end Alembic commands ###
